<a href="https://colab.research.google.com/github/sugutt/pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
print(torch.__version__)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

2.5.0+cu121


In [3]:
##Inroduction to tensor
##Scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int

In [6]:
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
#TENSOR


TENSOR = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

### Random tensors
Why random tensors?

Random tensors are important because the way neural tensors learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [16]:
#create a randomtensor of size (3, 4)

random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.2695, 0.5551, 0.6363, 0.2225],
        [0.2906, 0.1397, 0.2540, 0.4064],
        [0.0237, 0.1815, 0.8377, 0.0826]])

In [17]:
random_tensor.ndim

2

In [18]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
#create a tensorof all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#create a tensor of all ones
ones = torch.ones(size=(3,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

###Creating arange of tensors and tensor-like

In [22]:
one_to_ten =torch.arange(start=0,end=11, step=2)

In [23]:
#creating tensor-like
ten_zeroes= torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0])

###Tensor Datatypes

In [24]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                               device=None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
 float_16_tensor = float_32_tensor.type(torch.float16)
 float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

###manipulating tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [28]:
#create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [29]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [30]:
#subtract 10
tensor - 10

tensor([-9, -8, -7])

In [31]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performimg matrix multiplications need to satisfy:
1. The **inner dimensions** must match
2. The resulting matrix has the shape of the **outer dimensions**

In [33]:
#element-wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [34]:
#matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [35]:
 %%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.09 ms, sys: 16 µs, total: 2.1 ms
Wall time: 2.17 ms


In [36]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 85 µs, sys: 0 ns, total: 85 µs
Wall time: 89.9 µs


tensor(14)

In [37]:
# Shapes for matriix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]
                         ])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]
                         ])
#torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul (it's an alias for torch.matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [38]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [39]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [40]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [41]:


torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min,max, mean, sum , etc(tensor aggregation)

In [42]:
#create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [43]:
#find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [44]:
#find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [45]:
#find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [46]:
#find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##Finding the positional min and max

In [47]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [48]:
x.argmin()

tensor(0)

In [49]:
x[0]

tensor(1)

In [50]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [51]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - adds a 1 dimesion to a target tensor
* Permute - return a view of the input with dimensions permuted( swapped) in a certain way

In [52]:
#lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [53]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
#change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [55]:
#changing z changes x ( becausee a view of atensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [56]:
#stack tensors on top of each other
x_stcked = torch.stack([x, x, x, x], dim=0)
x_stcked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
#torch.squeeze() removes allsingle dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [58]:
# torch.unsqueeze() - adds a singledimension to a target tensor at a specific
# dim( dimension) %%
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [59]:
x_reshaped.shape

torch.Size([1, 9])

In [60]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
#torch.permute rearranges dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with pytorch is similar to indexing with numpy.

In [62]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
#let x be our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
#lets index onthe middle bracket (dim=1)
x[0] [0]

tensor([1, 2, 3])

In [65]:
#lets index the most inner bracket(last dimension)

In [66]:
x[0] [2][2]

tensor(9)

In [67]:
# You can also use ":" to select "all" of a tartget dimension
x[:, 0]

tensor([[1, 2, 3]])

In [68]:
# Get all values of the 0 dimensionbut only take the 1 index value of the first and 2nd dimension
x[:, 2,:]

tensor([[7, 8, 9]])

## PyTorch tensors & Numpy

Numpy is a popular scientific python numerical computing library

In [69]:
# Numpy array to a tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
array.dtype

dtype('float64')

In [71]:
#change the value of the array, what will this do to the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [72]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [73]:
# change the tensor, what hapens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns

`start with random numbers -> tensor operations -> update randomnumbers to try and make them of the data -> again -> again...`
To reduce the randomness of neural networks and pytorch comes the concept of **random seed**
Essentially, what the rendom seed does is "flavour" the randomness.

In [77]:
import torch

#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1209, 0.7515, 0.7893, 0.2248],
        [0.6765, 0.4988, 0.4909, 0.1469],
        [0.0189, 0.9034, 0.8802, 0.6617]])
tensor([[0.9446, 0.2707, 0.5944, 0.8441],
        [0.3526, 0.2410, 0.1239, 0.6679],
        [0.4647, 0.6343, 0.0741, 0.1387]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [80]:
#lets make some random reproducible tensor
import torch

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [3]:
!nvidia-smi

Fri Nov  8 19:51:32 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [4]:
import torch
torch.cuda.is_available()

True

For pytorch since its capable of running in a GPU or a CPU

In [5]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
torch.cuda.device_count()

1

In [7]:
## Putting tensors (and models) on the GPU

In [8]:
# cREATE A TENSOR (default on the Cpu)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [9]:
#Move tensor to GPU(If available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')